# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './assets/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(571, 600)
        MainWindow.setMinimumSize(QtCore.QSize(571, 600))
        MainWindow.setMaximumSize(QtCore.QSize(571, 600))
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./assets\\favicon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.tabWidget = QtWidgets.QTabWidget(MainWindow)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 571, 241))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.sourceExcelDirectoryPath = QtWidgets.QLineEdit(self.tab_3)
        self.sourceExcelDirectoryPath.setGeometry(QtCore.QRect(10, 30, 461, 20))
        self.sourceExcelDirectoryPath.setObjectName("sourceExcelDirectoryPath")
        self.sourceDirectoryButton = QtWidgets.QPushButton(self.tab_3)
        self.sourceDirectoryButton.setGeometry(QtCore.QRect(480, 30, 81, 21))
        self.sourceDirectoryButton.setObjectName("sourceDirectoryButton")
        self.convertExcelToHTMLActionButton = QtWidgets.QPushButton(self.tab_3)
        self.convertExcelToHTMLActionButton.setGeometry(QtCore.QRect(470, 170, 85, 31))
        self.convertExcelToHTMLActionButton.setObjectName("convertExcelToHTMLActionButton")
        self.savingDirectoryLable = QtWidgets.QLabel(self.tab_3)
        self.savingDirectoryLable.setGeometry(QtCore.QRect(10, 70, 381, 16))
        self.savingDirectoryLable.setObjectName("savingDirectoryLable")
        self.savingHTMLDirectoryPath = QtWidgets.QLineEdit(self.tab_3)
        self.savingHTMLDirectoryPath.setGeometry(QtCore.QRect(10, 90, 461, 20))
        self.savingHTMLDirectoryPath.setObjectName("savingHTMLDirectoryPath")
        self.savingDirectoryButton = QtWidgets.QPushButton(self.tab_3)
        self.savingDirectoryButton.setGeometry(QtCore.QRect(480, 90, 81, 21))
        self.savingDirectoryButton.setObjectName("savingDirectoryButton")
        self.progressBar = QtWidgets.QProgressBar(self.tab_3)
        self.progressBar.setEnabled(False)
        self.progressBar.setGeometry(QtCore.QRect(10, 170, 451, 31))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.sourceDirectoryLable = QtWidgets.QLabel(self.tab_3)
        self.sourceDirectoryLable.setGeometry(QtCore.QRect(10, 10, 391, 16))
        self.sourceDirectoryLable.setObjectName("sourceDirectoryLable")
        self.createNewDirectoryCheckBox = QtWidgets.QCheckBox(self.tab_3)
        self.createNewDirectoryCheckBox.setGeometry(QtCore.QRect(10, 120, 181, 18))
        self.createNewDirectoryCheckBox.setChecked(True)
        self.createNewDirectoryCheckBox.setObjectName("createNewDirectoryCheckBox")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.JSONDirectoryPath = QtWidgets.QLineEdit(self.tab_4)
        self.JSONDirectoryPath.setGeometry(QtCore.QRect(10, 60, 361, 20))
        self.JSONDirectoryPath.setObjectName("JSONDirectoryPath")
        self.JSONDirectoryPathActionButton = QtWidgets.QPushButton(self.tab_4)
        self.JSONDirectoryPathActionButton.setGeometry(QtCore.QRect(470, 60, 85, 21))
        self.JSONDirectoryPathActionButton.setObjectName("JSONDirectoryPathActionButton")
        self.labelJSONLavel_1 = QtWidgets.QLabel(self.tab_4)
        self.labelJSONLavel_1.setGeometry(QtCore.QRect(10, 10, 341, 16))
        self.labelJSONLavel_1.setObjectName("labelJSONLavel_1")
        self.labelJSONLavel_2 = QtWidgets.QLabel(self.tab_4)
        self.labelJSONLavel_2.setGeometry(QtCore.QRect(10, 40, 241, 16))
        self.labelJSONLavel_2.setObjectName("labelJSONLavel_2")
        self.JSONDirectoryPathChoiceButton = QtWidgets.QToolButton(self.tab_4)
        self.JSONDirectoryPathChoiceButton.setGeometry(QtCore.QRect(380, 60, 61, 21))
        self.JSONDirectoryPathChoiceButton.setObjectName("JSONDirectoryPathChoiceButton")
        self.tabWidget.addTab(self.tab_4, "")
        self.report = QtWidgets.QTextBrowser(MainWindow)
        self.report.setGeometry(QtCore.QRect(10, 270, 551, 321))
        self.report.setObjectName("report")
        self.reportLabel = QtWidgets.QLabel(MainWindow)
        self.reportLabel.setGeometry(QtCore.QRect(10, 250, 121, 16))
        self.reportLabel.setObjectName("reportLabel")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "schedule2html"))
        self.sourceDirectoryButton.setText(_translate("MainWindow", "Выбрать"))
        self.convertExcelToHTMLActionButton.setText(_translate("MainWindow", "Выполнить"))
        self.savingDirectoryLable.setText(_translate("MainWindow", "Выберете дирректорю сохранения расписаний в формате html"))
        self.savingDirectoryButton.setText(_translate("MainWindow", "Выбрать"))
        self.sourceDirectoryLable.setText(_translate("MainWindow", "Выберите дирректорию с расписанием файлов в формате excel"))
        self.createNewDirectoryCheckBox.setText(_translate("MainWindow", "Создать новый подкаталог?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Конвертирование Excel в html"))
        self.JSONDirectoryPathActionButton.setText(_translate("MainWindow", "Выполнить"))
        self.labelJSONLavel_1.setText(_translate("MainWindow", "Обновление JSON описания правил доступа к html файлам"))
        self.labelJSONLavel_2.setText(_translate("MainWindow", "Введите путь к каталогу с html файлами"))
        self.JSONDirectoryPathChoiceButton.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Дополнительные функции"))
        self.reportLabel.setText(_translate("MainWindow", "Отчет о выполнении"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
